#!/usr/bin/env python3
"""Generate `docs/STATUS.md` — what works today, counted from the tree.

    python3 scripts/status_summary.py            # write the page
    python3 scripts/status_summary.py --check    # fail if it is stale

**Why this exists.** The #290 audit asked for a "what works today" summary, and
the honest version of that is not a paragraph someone wrote once. Every number
here is counted from a document that is itself maintained for another reason:
bridge status rows in `BRIDGES.md`, the checklist in `HARDWARE.md`, the generated
`SECURITY_MATRIX.md`.

The failure mode being avoided is specific. A hand-written status page ages in
the flattering direction — a bridge gets marked "working" when its codec passes,
and nothing ever moves it back. Counting means a bridge that is still 🧪 keeps
saying so until someone runs it with a radio in their hand.
"""
import re
import sys
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "STATUS.md"

# Every status marker used in BRIDGES.md. A marker not listed here would land in
# an "unaccounted" bucket rather than being silently dropped: the first version of
# this script knew four markers, 🟡 was a fifth, and three bridges vanished from a
# page whose whole job is to be countable.
MARKERS = "✅🧪🟡⚪🚧"

BRIDGES = ROOT / "docs" / "BRIDGES.md"
HARDWARE = ROOT / "docs" / "HARDWARE.md"
MATRIX = ROOT / "docs" / "SECURITY_MATRIX.md"


def bridges():
    """(name, marker, status text) per bridge, from each section's Status row."""
    text = BRIDGES.read_text()
    out = []
    heading = None
    for line in text.splitlines():
        h = re.match(r"^#{2,3}\s+(.+?)\s*$", line)
        if h:
            heading = h.group(1)
            continue
        m = re.match(r"^\|\s*Status\s*\|\s*(.+?)\s*\|\s*$", line)
        if m and heading:
            status = m.group(1)
            seen = [c for c in MARKERS if c in status]
            # **More than one marker means more than one answer.** Meshtastic is
            # "✅ WiFi-UDP · 🧪 USB serial · 🧪 Web Serial & BLE": four pipes, two
            # of them never run on hardware. Taking the first marker filed it as
            # fully tested, which is the exact flattering drift this page exists
            # to stop, so a mixed line is its own bucket and keeps its whole text.
            marker = seen[0] if len(seen) == 1 else ("~" if seen else "?")
            prose = status.lstrip("".join(MARKERS) + " ").strip() if len(seen) == 1 else status
            out.append((heading, marker, prose))
            heading = None
    if not out:
        sys.exit("no bridge Status rows found — has BRIDGES.md changed shape?")
    return out


def hardware():
    """(rows, recorded) — how many procedures exist, and how many have a result."""
    text = HARDWARE.read_text()
    rows = re.findall(r"^\|\s*([0-9]+[a-z]?)\s*\|", text, re.M)
    # The file asks each runner to "note the date + result". A recorded run is a
    # row carrying a date. Nothing has one yet, and that is the point.
    recorded = len(re.findall(r"^\|\s*[0-9]+[a-z]?\s*\|.*\b20[0-9]{2}-[0-9]{2}-[0-9]{2}\b", text, re.M))
    return len(rows), recorded


def matrix():
    """(components, fuzzed, property_tested, reviewed, hardware)."""
    if not MATRIX.exists():
        sys.exit("docs/SECURITY_MATRIX.md is missing — run scripts/security_matrix.py")
    rows = [
        l for l in MATRIX.read_text().splitlines()
        if l.startswith("| **") and l.count("|") >= 7
    ]
    cols = [0, 0, 0, 0]
    for r in rows:
        cells = [c.strip() for c in r.split("|")[1:-1]]
        for i in range(4):
            if len(cells) > i + 1 and cells[i + 1].startswith("✅"):
                cols[i] += 1
    return (len(rows), *cols)


def build():
    bl = bridges()
    by = {}
    for name, marker, prose in bl:
        by.setdefault(marker, []).append((name, prose))
    hw_rows, hw_done = hardware()
    comps, fuzzed, propt, reviewed, hw_cov = matrix()

    verified = by.get("✅", [])
    untested = by.get("🧪", [])
    partial = by.get("🟡", []) + by.get("🚧", [])
    planned = by.get("⚪", [])
    mixed = by.get("~", [])
    unaccounted = by.get("?", [])
    assert (
        len(verified) + len(untested) + len(partial) + len(planned) + len(mixed) + len(unaccounted)
    ) == len(bl), "every bridge must land in exactly one bucket"

    lines = [
        "<!-- Generated by scripts/status_summary.py — do not edit by hand. -->",
        "",
        "# What works today",
        "",
        "Counted from the tree, not written from memory. A hand-maintained status page",
        "ages in the flattering direction — something gets marked working when its tests",
        "pass and nothing ever moves it back — so every number here is read out of a",
        "document that is maintained for another reason.",
        "",
        "## The short version",
        "",
        f"- **{len(verified)} of {len(bl)} bridges** are implemented and tested.",
        f"- **{len(untested)}** are implemented but have never been run against the real",
        "  hardware they are for. Their codecs are tested; the last hop is not.",
        f"- **{len(partial)}** are partly built — some of the path exists and some does not.",
        f"- **{len(mixed)}** carry more than one status at once, because they are several",
        "  paths under one name and those paths are not equally proved.",
        f"- **{len(planned)}** are planned and not written.",
        f"- **{hw_done} of {hw_rows}** hardware verification procedures have a recorded run.",
        f"- **{reviewed} of {comps}** components have had an independent security review.",
        "",
    ]

    if hw_done == 0:
        lines += [
            "**No hardware procedure has a recorded run**, and that is the most important",
            "line on this page. Everything marked 🧪 below is code that compiles, passes its",
            "codec tests, and has never met an antenna — a template to confirm against your",
            "own hardware, not a claim that it works.",
            "",
        ]
    if reviewed == 0:
        lines += [
            "**Nor has anything had an independent review.** Every fault on record was found",
            "by the same people who wrote the thing, which is a real method with a known",
            "blind spot: it finds what its authors thought to look for.",
            "",
        ]

    lines += [
        "## What you can actually do right now",
        "",
        "- Run a node **in a browser tab**, offline, from a single HTML file with no",
        "  external requests — and have two tabs talk over a loopback or WebSocket link.",
        "- Run a node **on Linux, macOS or Windows**, and on **Android**. Both are built",
        "  on every pull request.",
        "- Move messages over **anything that carries bytes**: a socket, a folder, a USB",
        "  stick, a serial cable. These are the paths CI exercises end to end.",
        "- **Rebuild the whole protocol from the documentation**, with decoders in C,",
        "  Python and shell that depend on nothing. See [Rebuild](REBUILD.md).",
        "",
        "## Bridges, by what has actually been proved",
        "",
        "### ✅ Implemented and tested",
        "",
    ]
    lines += [f"- **{n}** — {p}" for n, p in verified] or ["- (none)"]
    lines += [
        "",
        "### 🧪 Implemented, never run on the hardware it is for",
        "",
        "The codec is tested off-device; the radio, the tap, the live peer is not. Treat",
        "each as a template to confirm against your own hardware — the repeatable",
        "procedure is in [Hardware verification](HARDWARE.md).",
        "",
    ]
    lines += [f"- **{n}** — {p}" for n, p in untested] or ["- (none)"]
    if mixed:
        lines += [
            "",
            "### Several paths, unequally proved",
            "",
            "One name, more than one route, and not all of them tested. The full status",
            "line is reproduced rather than reduced to its best marker.",
            "",
        ]
        lines += [f"- **{n}** — {p}" for n, p in mixed]
    if partial:
        lines += [
            "",
            "### 🟡 Partly built",
            "",
            "Some of the path exists and some does not. Each row says which half.",
            "",
        ]
        lines += [f"- **{n}** — {p}" for n, p in partial]
    if unaccounted:
        lines += [
            "",
            "### Unaccounted",
            "",
            "These carry a status marker this script does not know. Listed rather than",
            "dropped, because a summary that quietly omits rows is worse than none.",
            "",
        ]
        lines += [f"- **{n}** — {p}" for n, p in unaccounted]
    if planned:
        lines += ["", "### ⚪ Planned, not written", ""]
        lines += [f"- **{n}**" for n, _ in planned]

    lines += [
        "",
        "## Testing, per component",
        "",
        f"Of {comps} components: **{fuzzed} fuzzed**, **{propt} property-tested**,",
        f"**{hw_cov} exercised by a hardware procedure**, **{reviewed} independently",
        "reviewed**. The per-component table, including what an attacker controls in",
        "each case, is [the security maturity matrix](SECURITY_MATRIX.md).",
        "",
        "## Where the numbers come from",
        "",
        "- Bridge rows: the `Status` line of each section in [Bridges](BRIDGES.md).",
        "- Hardware: rows in [the checklist](HARDWARE.md), and how many carry a date.",
        "  The file asks each runner to note the date and result; a row without one has",
        "  not been run, or the run was not written down, and those are the same thing",
        "  from here.",
        "- Components: [the security maturity matrix](SECURITY_MATRIX.md), which is",
        "  itself generated from the fuzz targets and test modules in the tree.",
    ]
    return "\n".join(lines) + "\n"


def main():
    page = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != page:
            print("docs/STATUS.md is stale — run: python3 scripts/status_summary.py")
            if OUT.exists():
                subprocess.run(["diff", "-u", str(OUT), "-"], input=page, text=True)
            sys.exit(1)
        print("STATUS OK — the summary matches what the documents say")
        return
    OUT.write_text(page)
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
