package org.spore.node

import android.provider.Settings
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsFocusedAsState
import androidx.compose.foundation.interaction.collectIsPressedAsState
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.sizeIn
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.TextFieldValue
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import org.spore.node.vendor.HardbrutDialog
import org.spore.node.vendor.HardbrutTokens
import org.spore.node.vendor.hardShadow

/**
 * The HARDBRUT chrome, in Compose.
 *
 * HARDBRUT (`supernihil/hardbrut`) upstream is normative; there is no
 * SPORE-authored design document to defer to instead. This file is HARDBRUT's
 * Android consumer, built on two vendored sources: `vendor/Hardbrut.kt`, the
 * official Compose port (tokens, `hardShadow()`), and `web/vendor/hardbrut/
 * hardbrut.css` for the one thing the Compose port doesn't define — dark mode
 * (see `Palette` below). HARDBRUT is light-first neubrutalism: cream
 * paper, black ink, yellow actions, zero border-radius (true circles excepted),
 * hard no-blur shadows that stay on every element and vanish only on press. Two
 * button kinds — default (yellow) and cancel (white).
 *
 * Two rules from the spec are load-bearing here and easy to undo by accident:
 *
 *  * **Hard edges.** Zero-corner radius and a *hard offset* shadow with no blur.
 *    Compose's `Modifier.shadow` draws a blurred elevation shadow, which is the
 *    Material look this language exists to avoid — so [crate] and [CrateButton]
 *    draw it via the vendored `hardShadow()` instead. Reach for `shadow()` here
 *    and the crate stops being a crate.
 *  * **Never signal failure by colour alone.** HARDBRUT has no red; error and
 *    danger states pair an icon with words, never rely on a hue.
 */

// -- palette ------------------------------------------------------------------

// >>> design tokens: generated by design/generate.py — do not edit <<<
/**
 * HARDBRUT's palette. The light half aliases the vendored Compose port
 * (`vendor/Hardbrut.kt`'s `HardbrutTokens`) directly — not a copied colour.
 * The dark half has no equivalent there (that file defines no dark-mode
 * variant), so design/generate.py parses it from the vendored `hardbrut.css`
 * instead — the one gap between SPORE's two vendored HARDBRUT sources.
 *
 * HARDBRUT is light-first: the primary members are the light theme, and the
 * identical names + `Dark` are the dark theme. Two button kinds (Yellow default,
 * Paper cancel); black ink; zero radius; hard no-blur shadows.
 */
internal object Palette {
    val Ink = HardbrutTokens.Ink                   // text, borders, chrome
    val Paper = HardbrutTokens.Paper               // cards on paper
    val Yellow = HardbrutTokens.AccentYellow.first // primary actions, highlights — the one colour shared by both themes
    val Muted = HardbrutTokens.Muted               // de-emphasised text
    val Bg = HardbrutTokens.Background             // page base

    // Dark mode — inverted ink/paper; the yellow accent is unchanged. Ink/
    // Paper/Muted/Bg come from the vendored hardbrut.css's [data-theme="dark"]
    // block (HardbrutTokens has no dark-mode variant to alias here).
    val InkDark = Color(0xFFF0F0E8)                    // text, borders, chrome
    val PaperDark = Color(0xFF1A1A18)                  // cards on paper
    val YellowDark = HardbrutTokens.AccentYellow.first // primary actions, highlights — the one colour shared by both themes
    val MutedDark = Color(0xFFA0A090)                  // de-emphasised text
    val BgDark = Color(0xFF121210)                     // page base
    val OnYellow = HardbrutTokens.AccentYellow.second  // text sitting on the yellow face — unchanged between themes
}

/**
 * Sizing, spacing and shape — control/chip/row are SPORE's own Android
 * decision (design/tokens.json); radius/border/throw/spacing alias the vendored
 * `vendor/Hardbrut.kt`'s `HardbrutTokens`. Hand-typing a button height or a
 * shadow offset here is a CI failure for the same reason hand-typing a hex is.
 */
internal object Metrics {
    val ControlH = 48.dp                 // primary and secondary buttons, and text fields — one height for all three
    val ControlPX = 14.dp                // horizontal padding
    val ControlPY = 9.dp                 // vertical padding
    val ChipH = 32.dp                    // compact presets and toggles (offline-window, topics). Must still carry a 48dp touch target
    val ChipPX = 10.dp                   // horizontal padding
    val ChipPY = 4.dp                    // vertical padding
    val RowH = 56.dp                     // list rows — the unit the Bridges/Advanced restructure is built from
    val RowPX = 12.dp                    // horizontal padding
    val RowPY = 8.dp                     // vertical padding
    val Radius = 0.dp                    // corner radius — zero, always. Neither vendored HARDBRUT source defines one; it simply never sets one (true circles are the only exception)
    val Border = HardbrutTokens.Border   // border width — HARDBRUT's Border
    val Throw = HardbrutTokens.Shadow    // the hard no-blur drop-shadow offset — HARDBRUT's Shadow
    val Tight = HardbrutTokens.SpaceSm   // tighter internal padding — HARDBRUT's SpaceSm
    val Gap = HardbrutTokens.SpaceSm     // between controls — HARDBRUT's SpaceSm
    val Pad = HardbrutTokens.Space       // inside a card / crate — HARDBRUT's Space
    val Section = HardbrutTokens.SpaceLg // between sections — HARDBRUT's SpaceLg
    val TouchMin = 48.dp                 // WCAG/Material floor. control and row clear it by height; chip must be padded out to it.
}
// >>> end design tokens <<<

/** Hard-edged everywhere: §3 allows 2 dp and no more. */
internal val CrateShape = RoundedCornerShape(Metrics.Radius)

// HARDBRUT is light-first: cream paper, black ink, yellow actions. Dark is the
// inverted twin, sharing only the yellow accent.
internal val SporeLightColors = lightColorScheme(
    primary = Palette.Yellow,
    secondary = Palette.Ink,
    tertiary = Palette.Ink,
    background = Palette.Bg,
    surface = Palette.Paper,
    surfaceVariant = Palette.Paper,
    onBackground = Palette.Ink,
    onSurface = Palette.Ink,
    onPrimary = Palette.Ink,
    outline = Palette.Ink,
    error = Palette.Ink,
)

internal val SporeDarkColors = darkColorScheme(
    primary = Palette.YellowDark,
    secondary = Palette.InkDark,
    tertiary = Palette.InkDark,
    background = Palette.BgDark,
    surface = Palette.PaperDark,
    surfaceVariant = Palette.PaperDark,
    onBackground = Palette.InkDark,
    onSurface = Palette.InkDark,
    onPrimary = Palette.OnYellow,
    outline = Palette.InkDark,
    // HARDBRUT has no red — failure is an icon plus words, never colour alone.
    error = Palette.InkDark,
)

/**
 * §2: everything is monospace, because this is a terminal. Applied as a whole
 * [Typography] so a plain `Text` is right by default and nobody has to remember.
 * No downloaded font anywhere — constraint 1 forbids it and CI greps for it.
 */
internal val SporeTypography: Typography = Typography().let { d ->
    fun TextStyle.mono() = copy(fontFamily = FontFamily.Monospace)
    Typography(
        displayLarge = d.displayLarge.mono(), displayMedium = d.displayMedium.mono(),
        displaySmall = d.displaySmall.mono(), headlineLarge = d.headlineLarge.mono(),
        headlineMedium = d.headlineMedium.mono(), headlineSmall = d.headlineSmall.mono(),
        titleLarge = d.titleLarge.mono(), titleMedium = d.titleMedium.mono(),
        titleSmall = d.titleSmall.mono(), bodyLarge = d.bodyLarge.mono(),
        bodyMedium = d.bodyMedium.mono(), bodySmall = d.bodySmall.mono(),
        labelLarge = d.labelLarge.mono(), labelMedium = d.labelMedium.mono(),
        labelSmall = d.labelSmall.mono(),
    )
}

// -- reduced motion -----------------------------------------------------------

/**
 * Android's equivalent of `prefers-reduced-motion: reduce`.
 *
 * There is no Compose API for this. The platform signal is the animator duration
 * scale, which Developer Options and the accessibility "remove animations" toggle
 * both drive to 0. Read once per composition rather than per frame — it changes
 * about as often as a device reboot, and polling it in a draw scope would be
 * absurd.
 *
 * Constraint 2 says the interface must be *completely* static under this, not
 * merely calmer: a CRT flicker is a photosensitivity trigger.
 */
@Composable
internal fun reducedMotion(): Boolean {
    val ctx = LocalContext.current
    return remember(ctx) {
        runCatching {
            Settings.Global.getFloat(ctx.contentResolver, Settings.Global.ANIMATOR_DURATION_SCALE, 1f) == 0f
        }.getOrDefault(false)
    }
}

// -- the crate ----------------------------------------------------------------

/**
 * HARDBRUT's container: paper fill, 3 px ink border, hard no-blur offset shadow,
 * zero rounding.
 *
 * The shadow is painted into reserved padding rather than outside the layout
 * bounds, so a crate never bleeds over its neighbour in a `Column`. That is why
 * the padding comes first: it shrinks the draw area to the visible face and
 * leaves exactly [depth] on the shadow side.
 */
internal fun Modifier.crate(
    fill: Color = Palette.Paper,
    edge: Color = Palette.Ink,
    depth: Dp = Metrics.Throw,
): Modifier = this
    .padding(end = depth, bottom = depth)
    // The vendored hardShadow() draws the same offset rect this used to hand-roll;
    // pinned to Color.Black (not its Ink-defaulted colour) so the shadow reads as a
    // shadow rather than going near-white in dark mode, where Ink is near-white.
    .hardShadow(depth, Color.Black)
    .background(fill, CrateShape)
    .border(Metrics.Border, edge, CrateShape)

/** A crate as a container. [edge] carries meaning — pink for danger, cyan for focus. */
@Composable
internal fun Crate(
    modifier: Modifier = Modifier,
    fill: Color = Palette.Paper,
    edge: Color = Palette.Ink,
    content: @Composable () -> Unit,
) {
    Box(modifier.crate(fill, edge).padding(Metrics.Pad)) { content() }
}

// -- display heading ----------------------------------------------------------

/**
 * §2 headers: uppercase, heavy, tight tracking, amber, with the 2 px CRT bloom.
 *
 * The spec names Impact/Haettenschweiler; constraint 1 forbids downloading them
 * and neither ships on Android. `FontWeight.Black` on the system sans is the
 * closest honest stand-in — condensed-ness is the part we lose, and pretending
 * otherwise by shipping a webfont would break the standalone's zero-request rule.
 *
 * The bloom is a real 2 px blur via [Shadow], dropped under reduced motion where
 * §2 says it reads as blur rather than glow.
 */
@Composable
internal fun DisplayHeading(
    text: String,
    modifier: Modifier = Modifier,
    color: Color = MaterialTheme.colorScheme.onBackground,
    size: Int = 20,
) {
    Text(
        text.uppercase(),
        modifier,
        color = color,
        maxLines = 1,
        overflow = TextOverflow.Ellipsis,
        style = TextStyle(
            // HARDBRUT: bold uppercase display, no CRT bloom.
            fontFamily = FontFamily.SansSerif,
            fontWeight = FontWeight.Black,
            fontSize = size.sp,
            letterSpacing = (-0.02 * size).sp,
        ),
    )
}

// -- the Toughbook input ------------------------------------------------------

/**
 * §3's input: an inset `--void` field, 2 px `--edge` border, four 3 px "screw"
 * dots in `--kevlar` at the corners. Focus *thickens* the border to a 2 px cyan
 * ring — §7 says never remove the focus indicator, so this replaces it rather
 * than suppressing it.
 *
 * [BasicTextField] rather than `OutlinedTextField`: the Material one carries its
 * own rounded container and label animation, which is the look being replaced.
 */
@Composable
internal fun ToughbookField(
    value: String,
    onValueChange: (String) -> Unit,
    modifier: Modifier = Modifier,
    placeholder: String = "",
    singleLine: Boolean = true,
    minHeight: Dp = 44.dp,
    enabled: Boolean = true,
) {
    val interaction = remember { MutableInteractionSource() }
    val focused by interaction.collectIsFocusedAsState()
    val border = if (focused) Palette.Ink else Palette.Ink

    BasicTextField(
        value = value,
        onValueChange = onValueChange,
        modifier = modifier,
        enabled = enabled,
        singleLine = singleLine,
        textStyle = TextStyle(
            fontFamily = FontFamily.Monospace,
            fontSize = 13.sp,
            color = MaterialTheme.colorScheme.onSurface,
        ),
        cursorBrush = SolidColor(Palette.Yellow), // §3: the cursor is the kawaii accent
        interactionSource = interaction,
    ) { inner ->
        ToughbookFace(value, placeholder, border, singleLine, minHeight, inner)
    }
}

/**
 * [ToughbookField] over a [TextFieldValue].
 *
 * The composer's markdown toolbar has to insert at the cursor, which means the
 * caller owns the selection — a `String`-valued field cannot express that, and
 * rebuilding a `TextFieldValue` from the text on every keystroke would slam the
 * caret to the end and make it impossible to edit anywhere but the tail.
 */
@Composable
internal fun ToughbookField(
    value: TextFieldValue,
    onValueChange: (TextFieldValue) -> Unit,
    modifier: Modifier = Modifier,
    placeholder: String = "",
    singleLine: Boolean = true,
    minHeight: Dp = 44.dp,
    enabled: Boolean = true,
) {
    val interaction = remember { MutableInteractionSource() }
    val focused by interaction.collectIsFocusedAsState()
    val border = if (focused) Palette.Ink else Palette.Ink

    BasicTextField(
        value = value,
        onValueChange = onValueChange,
        modifier = modifier,
        enabled = enabled,
        singleLine = singleLine,
        textStyle = TextStyle(
            fontFamily = FontFamily.Monospace,
            fontSize = 13.sp,
            color = MaterialTheme.colorScheme.onSurface,
        ),
        cursorBrush = SolidColor(Palette.Yellow),
        interactionSource = interaction,
    ) { inner ->
        ToughbookFace(value.text, placeholder, border, singleLine, minHeight, inner)
    }
}

/** The shared frame: inset void face, screws, focus ring. */
@Composable
private fun ToughbookFace(
    text: String,
    placeholder: String,
    border: Color,
    singleLine: Boolean,
    minHeight: Dp,
    inner: @Composable () -> Unit,
) {
    val screw = 3.dp
    Box(
        Modifier
            .fillMaxWidth()
            .background(Palette.Paper, CrateShape)
            .border(2.dp, border, CrateShape)
            .drawBehind {
                // Four screws. Inset by the border so they sit on the face,
                // not on the frame.
                val d = screw.toPx()
                val m = 3.dp.toPx()
                listOf(
                    Offset(m, m),
                    Offset(size.width - m - d, m),
                    Offset(m, size.height - m - d),
                    Offset(size.width - m - d, size.height - m - d),
                ).forEach { drawRect(Palette.Muted, it, Size(d, d)) }
            }
            .padding(horizontal = 10.dp, vertical = 10.dp)
            .then(if (singleLine) Modifier else Modifier.height(minHeight)),
    ) {
        if (text.isEmpty() && placeholder.isNotEmpty()) {
            Text(
                placeholder,
                color = Palette.Muted,
                style = TextStyle(fontFamily = FontFamily.Monospace, fontSize = 13.sp),
            )
        }
        inner()
    }
}

// -- the radio switch ---------------------------------------------------------

/**
 * §3's button: a chunky `--kevlar` face with a 3 px hard drop-shadow and an
 * `--amber` uppercase label. Pressing translates it 3 px down-right and drops the
 * shadow to zero — the throw is the whole point, so it is position *and* shadow,
 * not a ripple.
 *
 * Amber on olive is 4.48:1, which §1 permits for large text only. The label is
 * therefore 15 sp bold, clearing WCAG's 14 pt-bold threshold. Shrink it and the
 * button quietly becomes unreadable.
 *
 * The spec also asks for a clack and a particle burst on press. Sound is off
 * until the user enables it and there is no such setting yet, so neither is wired
 * here rather than being wired on-by-default — §7's "sound off by default" is not
 * something to get wrong once and ship.
 *
 * @param contentDescription Overrides the accessible name for an icon/symbol-only
 * [label] (e.g. "📎") that TalkBack can't otherwise read meaningfully — leave null
 * for a word label, where [label] itself is already the right thing to announce.
 */
@Composable
internal fun CrateButton(
    label: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    enabled: Boolean = true,
    face: Color = Palette.Muted,
    ink: Color = Palette.Ink,
    contentDescription: String? = null,
) {
    val interaction = remember { MutableInteractionSource() }
    val pressed by interaction.collectIsPressedAsState()
    val throwDp = Metrics.Throw
    val down = pressed && enabled

    Box(
        modifier
            .padding(end = throwDp, bottom = throwDp)
            .then(if (down) Modifier.offset(throwDp, throwDp) else Modifier)
            // The throw is the feedback: shadow while at rest, gone (offset above
            // takes its place) while pressed — hardShadow() only draws the resting half.
            .then(if (!down) Modifier.hardShadow(throwDp, Color.Black.copy(alpha = 0.6f)) else Modifier)
            // A real touch target, not an invisible hitbox around a smaller-looking
            // button (B7) — every CrateButton was under the 48dp floor before this.
            .sizeIn(minWidth = Metrics.TouchMin, minHeight = Metrics.ControlH)
            .background(if (enabled) face else Palette.Paper, CrateShape)
            .border(2.dp, Palette.Ink, CrateShape)
            .radioClickable(interaction, enabled, onClick)
            .then(
                if (contentDescription != null) {
                    Modifier.semantics { this.contentDescription = contentDescription }
                } else Modifier
            )
            .padding(horizontal = Metrics.ControlPX, vertical = Metrics.ControlPY),
        contentAlignment = Alignment.Center,
    ) {
        Text(
            label.uppercase(),
            // The description above replaces this text as the accessible name —
            // without clearing it, TalkBack would merge and read both (B7).
            modifier = if (contentDescription != null) Modifier.clearAndSetSemantics {} else Modifier,
            color = if (enabled) ink else Palette.Muted,
            style = TextStyle(
                fontFamily = FontFamily.Monospace,
                fontWeight = FontWeight.Bold,
                fontSize = 15.sp, // ≥14 pt bold — the floor for amber-on-olive
                letterSpacing = 0.05.sp,
            ),
        )
    }
}

/**
 * Clickable without Material's ripple — the throw is the feedback (§3).
 *
 * `clickable` is an extension on [Modifier], so it has to be called on the
 * receiver. Writing it fully qualified does not resolve an extension.
 */
private fun Modifier.radioClickable(
    interaction: MutableInteractionSource,
    enabled: Boolean,
    onClick: () -> Unit,
): Modifier = this.clickable(
    interactionSource = interaction,
    indication = null,
    enabled = enabled,
    onClick = onClick,
)

// -- segmented LED ------------------------------------------------------------

/**
 * §3's progress: discrete blocks, never a smooth bar, because this machine counts.
 * Used for fountain-chunk progress, where the count is the actual unit of work.
 */
@Composable
internal fun SegmentedLed(
    have: Int,
    total: Int,
    modifier: Modifier = Modifier,
    segments: Int = 8,
    height: Dp = 6.dp,
    on: Color = Palette.Ink,
) {
    val n = segments.coerceAtLeast(1)
    val lit = if (total <= 0) 0 else ((have.toFloat() / total) * n).toInt().coerceIn(0, n)
    Row(modifier, horizontalArrangement = Arrangement.spacedBy(2.dp)) {
        repeat(n) { i ->
            Box(
                Modifier
                    .weight(1f)
                    .height(height)
                    .background(if (i < lit) on else Palette.Muted),
            )
        }
    }
}

// -- badges and status dots ---------------------------------------------------

/**
 * §3's sticker. Rotation is deliberately not offered: it was rejected during
 * design review, and a rotated badge over live text is a legibility problem
 * dressed as personality.
 *
 * [bg] defaults to void so a pink badge is legal — pink on kevlar is 2.32:1 and
 * the one pairing §1 bans, which is exactly the mistake this signature prevents
 * by not defaulting the background to the crate fill.
 */
@Composable
internal fun StickerBadge(
    text: String,
    modifier: Modifier = Modifier,
    ink: Color = Palette.Ink,
    bg: Color = Palette.Paper,
    edge: Color = ink,
) {
    Text(
        text,
        modifier
            .background(bg, CrateShape)
            .border(2.dp, edge, CrateShape)
            .padding(horizontal = 6.dp, vertical = 2.dp),
        color = ink,
        maxLines = 1,
        style = TextStyle(
            fontFamily = FontFamily.Monospace,
            fontWeight = FontWeight.Bold,
            fontSize = 10.sp,
        ),
    )
}

/** Link state as a dot. Never the only signal — §1 forbids colour-alone. */
@Composable
internal fun LedDot(color: Color, modifier: Modifier = Modifier, size: Dp = 8.dp) {
    Box(modifier.size(size).background(color, CircleShape))
}

/**
 * A crate-faced toggle. Material's `Switch` is a rounded pill with a ripple; this
 * is the same control drawn as hardware.
 */
@Composable
internal fun CrateSwitch(
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit,
    modifier: Modifier = Modifier,
    enabled: Boolean = true,
) {
    val interaction = remember { MutableInteractionSource() }
    Box(
        modifier
            .size(width = 40.dp, height = 22.dp)
            .background(if (checked) Palette.Ink else Palette.Muted, CrateShape)
            .border(2.dp, Palette.Ink, CrateShape)
            .radioClickable(interaction, enabled) { onCheckedChange(!checked) }
            .padding(2.dp),
        contentAlignment = if (checked) Alignment.CenterEnd else Alignment.CenterStart,
    ) {
        Box(Modifier.size(width = 14.dp, height = 14.dp).background(Palette.Paper, CrateShape))
    }
}

/** A section rule for grouped lists (Radio / Network / Web on Bridges). */
@Composable
internal fun SectionLabel(text: String, modifier: Modifier = Modifier) {
    Text(
        text.uppercase(),
        modifier.padding(top = 10.dp, bottom = 4.dp),
        color = Palette.Muted,
        style = TextStyle(
            fontFamily = FontFamily.Monospace,
            fontSize = 10.sp,
            letterSpacing = 0.08.sp,
        ),
    )
}

/** Caption text — the `--dim` role, 4.68:1 on void. */
@Composable
internal fun Caption(text: String, modifier: Modifier = Modifier, color: Color = Palette.Muted) {
    Text(
        text,
        modifier,
        color = color,
        style = TextStyle(fontFamily = FontFamily.Monospace, fontSize = 11.sp),
    )
}

/**
 * A modal yes/no for an action that can't be taken back — a PUBLIC broadcast, say.
 * The confirm button is the default yellow face; Cancel is the quiet default and
 * dismissing the dialog also cancels. Built on the vendored `HardbrutDialog`
 * rather than Material3's `AlertDialog`, same reasoning as [crate]'s `hardShadow`:
 * Material3's own dialog chrome (rounded corners, its own elevation) fights the
 * zero-radius, hard-shadow look everywhere else.
 */
@Composable
internal fun ConfirmDialog(
    title: String,
    body: String,
    confirmLabel: String,
    onConfirm: () -> Unit,
    onDismiss: () -> Unit,
) {
    HardbrutDialog(onDismissRequest = onDismiss) {
        DisplayHeading(title, size = 15)
        VGap(6.dp)
        Caption(body)
        VGap(Metrics.Pad)
        Row(horizontalArrangement = Arrangement.spacedBy(Metrics.Gap)) {
            CrateButton(confirmLabel, onConfirm, face = Palette.Yellow, ink = Palette.Paper)
            CrateButton("Cancel", onDismiss)
        }
    }
}

/** Horizontal gap, spelled once. */
@Composable
internal fun HGap(w: Dp = 8.dp) = Spacer(Modifier.width(w))

/** Vertical gap, spelled once. */
@Composable
internal fun VGap(h: Dp = Metrics.Gap) = Spacer(Modifier.height(h))

/**
 * §3's CHIP: a compact 32dp preset/toggle — topics, time windows, radio
 * quick-params. Rendered as a small kevlar crate with the throw flattened to 2dp
 * and a 48dp invisible touch target extending past the visible face so WCAG's
 * floor is met without a 48dp visual button (C5).
 *
 * [selected] flips the face to [activeFill] and ink to [activeInk]; the default
 * selections use pink-face-with-void-ink to keep pink off kevlar.
 */
@Composable
internal fun Chip(
    label: String,
    selected: Boolean,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    enabled: Boolean = true,
    activeFill: Color = Palette.Yellow,
    activeInk: Color = Palette.Paper,
    inactiveFill: Color = Palette.Muted,
    inactiveInk: Color = Palette.Ink,
    contentDescription: String? = null,
) {
    val interaction = remember { MutableInteractionSource() }
    val pressed by interaction.collectIsPressedAsState()
    val down = pressed && enabled
    val fill = if (selected) activeFill else inactiveFill
    val ink = if (selected) activeInk else inactiveInk
    val throwDp = 2.dp

    Box(
        modifier
            // Touch target: 48dp min. The visual chip is 32dp; the extra is
            // invisible padding that carries the clickable area.
            .sizeIn(minWidth = Metrics.TouchMin, minHeight = Metrics.TouchMin)
            .padding(end = throwDp, bottom = throwDp)
            .then(if (down) Modifier.offset(throwDp, throwDp) else Modifier)
            .then(if (!down) Modifier.hardShadow(throwDp, Color.Black.copy(alpha = 0.5f)) else Modifier)
            .background(if (enabled) fill else Palette.Paper, CrateShape)
            .border(2.dp, Palette.Ink, CrateShape)
            .radioClickable(interaction, enabled, onClick)
            .then(
                if (contentDescription != null) {
                    Modifier.semantics { this.contentDescription = contentDescription }
                } else Modifier
            )
            .padding(horizontal = Metrics.ChipPX, vertical = Metrics.ChipPY),
        contentAlignment = Alignment.Center,
    ) {
        Text(
            label.uppercase(),
            modifier = if (contentDescription != null) Modifier.clearAndSetSemantics {} else Modifier,
            color = if (enabled) ink else Palette.Muted,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis,
            style = TextStyle(
                fontFamily = FontFamily.Monospace,
                fontWeight = FontWeight.Bold,
                fontSize = 11.sp,
                letterSpacing = 0.05.sp,
            ),
        )
    }
}

/**
 * A 56dp list row for the Bridges/Advanced restructure (C6): uniform height,
 * label + value + trailing action. The crate shadow faces right so rows stack
 * without overlapping shadows.
 *
 * [trailing] replaces the default chevron ("›") when non-null. Pass a
 * [CrateSwitch] for a toggle, a [StickerBadge] for a status badge, or
 * null to suppress the trailing element entirely.
 */
@Composable
internal fun ListRow(
    label: String,
    modifier: Modifier = Modifier,
    value: String? = null,
    trailing: @Composable (() -> Unit)? = null,
    onClick: (() -> Unit)? = null,
    enabled: Boolean = true,
) {
    val interaction = remember { MutableInteractionSource() }
    val pressed by interaction.collectIsPressedAsState()
    val down = pressed && enabled && onClick != null
    val throwDp = Metrics.Throw

    val rowModifier = modifier
        .fillMaxWidth()
        .height(Metrics.RowH)
        .padding(end = throwDp, bottom = throwDp)
        .then(if (down) Modifier.offset(throwDp, throwDp) else Modifier)
        .then(if (!down) Modifier.hardShadow(throwDp, Color.Black.copy(alpha = 0.6f)) else Modifier)
        .background(Palette.Paper, CrateShape)
        .border(2.dp, Palette.Ink, CrateShape)
        .padding(horizontal = Metrics.RowPX, vertical = Metrics.RowPY)

    val clickMod = if (onClick != null) {
        rowModifier.radioClickable(interaction, enabled, onClick)
    } else rowModifier

    Row(
        clickMod,
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(
            label,
            modifier = Modifier.weight(1f),
            color = MaterialTheme.colorScheme.onSurface,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis,
            style = TextStyle(
                fontFamily = FontFamily.Monospace,
                fontSize = 13.sp,
            ),
        )
        if (value != null) {
            Caption(value, Modifier.padding(start = 8.dp))
        }
        if (trailing != null) {
            Box(Modifier.padding(start = 8.dp)) { trailing() }
        } else if (onClick != null) {
            Text(
                "›",
                color = Palette.Muted,
                style = TextStyle(fontFamily = FontFamily.Monospace, fontSize = 16.sp),
            )
        }
    }
}
